export enum UserRole {
  CONSUMER = 'CONSUMER',
  MERCHANT = 'MERCHANT',
  GUEST = 'GUEST'
}

export enum AppScreen {
  LOGIN = 'LOGIN',
  HOME = 'HOME',
  AVATAR = 'AVATAR',
  MERCHANT_DASHBOARD = 'MERCHANT_DASHBOARD',
  SUPPORT = 'SUPPORT',
  HOT_PRODUCTS = 'HOT_PRODUCTS',
  COMMUNITY = 'COMMUNITY',
  LIVE_STREAM = 'LIVE_STREAM',
  PROFILE = 'PROFILE',
  LIVE_ROOM_CUSTOMIZE = 'LIVE_ROOM_CUSTOMIZE'
}